### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by chrisnevers** [sanette/ocaml-api#1]
Hey, could you update the README with instructions on how to build and run the project? I want to hack around with the styling, but 
```
dune build
dune exec process
```
is not working for me. I'm not sure how to run the project.

**Comment by sanette** [comment]
oh yes it's not clean on that side, sorry.
For the moment you need to download yourself the manual sources, and
run `dune exec src/process.exe` to process all the html files.
And then copy the css and js files to the docs/ directory.

I'll put this on the README

**Comment by sanette** [comment]
done. Also added a Makefile. Tell me if it works for you.

**Comment by chrisnevers** [comment]
Thanks, works great! 🙂

**Comment by sanette** [comment]
I've added some options to the script, see README
