### ISSUE TITLE
adding a favicon ?

### ISSUE THREAD

**Issue by redianthus** [sanette/ocaml-api#2]
Hiya,

I bookmarked a link to the API, but as there's no favicon atm it's not always easy to find it back. Would you be OK to add a favicon ? Ideally it would be different from the one used e.g. on discuss (and ocaml.org) so it's easily findable.

Cheers !

**Comment by sanette** [comment]
sure, why not? although there is some hope that (a version of) this page will be eventually integrated into ocaml.org. Do you have artistic skills?

**Comment by sanette** [comment]
something like this?
[ocaml-api-icon.pdf](https://github.com/sanette/ocaml-api/files/4606426/ocaml-api-icon.pdf)
![ocaml-api-icon](https://user-images.githubusercontent.com/7536536/81507109-4f1d7a80-92fb-11ea-8e27-c08fb034709d.png)
(the ocaml icon is released under UNLICENCE, so it should be fine with them)

**Comment by redianthus** [comment]
> Do you have artistic skills?

No. :)

> something like this?

Yes, that's fine !

**Comment by sanette** [comment]
well, ok, let's try this one. Done.
