### ISSUE TITLE
suggestion to update the css for table

### ISSUE THREAD

**Issue by arbipher** [sanette/ocaml-api#3]
The table doesn't look alike between [yours](https://sanette.github.io/ocaml-tutorial/4.10/expr.html#ss:precedence-and-associativity) and [official](https://caml.inria.fr/pub/docs/manual-ocaml/expr.html#ss:precedence-and-associativity).

**Comment by sanette** [comment]
thanks for notifying. I'll try to fix this asap

**Comment by sanette** [comment]
this should be better now

**Comment by sanette** [comment]
note: this issue actually belongs to https://github.com/sanette/ocaml-tutorial

**Comment by arbipher** [comment]
Cool. It's much better. I will report to that repo for other issues.
